---
- name: Copy boot overlay DTB files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
  with_items:
    - src: "boot/overlays/{{ overlay_dtb_file }}"
      dest: "{{ boot_overlays_dir }}"
    - src: "boot/overlays/{{ overlay_dtb_file }}"
      dest: "{{ boot_overlays_dir }}{{ overlay_dtbo_file }}"
  notify:
    - Reboot host and wait for it to restart

- name: Copy fresh boot config
  ansible.builtin.copy:
    src: boot/config.txt
    dest: "{{ boot_config_dir }}config.txt"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
    force: no

- name: Configure boot config
  ansible.builtin.lineinfile:
    path: "{{ boot_config_dir }}config.txt"
    state: present
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items: "{{ lcd_boot_config_options }}"
  notify:
    - Reboot host and wait for it to restart

- name: Copy cmdline file
  ansible.builtin.template:
    src: boot/cmdline.txt.j2
    dest: "{{ boot_config_dir }}cmdline.txt"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
  when: ansible_distribution == 'Debian'
  notify:
    - Reboot host and wait for it to restart

- name: Copy inittab file
  ansible.builtin.copy:
    src: etc/inittab
    dest: /etc/inittab
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x
  when: ansible_distribution == 'Debian'
  notify:
    - Reboot host and wait for it to restart
