---
# Variable setup
- name: Check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - lcd_size

- include: raspbian-facts.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu-facts.yml
  when: ansible_distribution == 'Ubuntu'

# Configure LCD
- import_tasks: configure-boot.yml
- import_tasks: configure-x11.yml
- import_tasks: configure-touch.yml
