---
- import_tasks: required-vars.yml

- include: raspbian-facts.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu-facts.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: boot-config.yml

- import_tasks: x11-config.yml

- import_tasks: touch-config.yml
