---
# Variable setup
- name: Check required variables
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - lcd_type

- name: Validate LCD type
  ansible.builtin.fail:
    msg: "LCD type '{{ lcd_type }}' is not supported"
  when: lcd_type not in ['MPI3501']

- name: Include distribution-specific vars.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"

- name: Define distribution facts
  ansible.builtin.set_fact:
    boot_config_dir: "{{ __boot_config_dir }}"
    boot_overlays_dir: "{{ __boot_overlays_dir }}"

- name: Include LCD type-specific vars.
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ lcd_type }}.yml"

- name: Validate LCD rotate
  ansible.builtin.fail:
    msg: "LCD rotate '{{ lcd_rotate }}' is not supported on {{ lcd_type }}"
  when: lcd_rotate not in __lcd_calibrations.keys()

- name: Define LCD type facts
  ansible.builtin.set_fact:
    overlay_dtb_file: "{{ __overlay_dtb_file }}"
    overlay_dtbo_file: "{{ __overlay_dtbo_file }}"
    lcd_boot_config_options: "{{ __lcd_boot_config_options }}"
    lcd_calibration: "{{ __lcd_calibrations[lcd_rotate] }}"
    lcd_swap_axes: "{{ __lcd_swap_axes }}"

- name: Include Raspbian facts
  ansible.builtin.include_tasks: raspbian-facts.yml
  when: ansible_distribution == 'Debian'

# Configure LCD
- name: Import configure boot tasks
  ansible.builtin.import_tasks: configure-boot.yml
- name: Import configure x11 tasks
  ansible.builtin.import_tasks: configure-x11.yml
- name: Import configure touch tasks
  ansible.builtin.import_tasks: configure-touch.yml
