---
# Variable setup
- name: Check required variables
  fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items:
    - lcd_type

- name: Include distribution-specific vars.
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}.yml"
      skip: true

- name: Define boot_config_dir.
  set_fact:
    boot_config_dir: "{{ __boot_config_dir }}"

- name: Define boot_overlays_dir.
  set_fact:
    boot_overlays_dir: "{{ __boot_overlays_dir }}"

- include: raspbian-facts.yml
  when: ansible_distribution == 'Debian'

# Configure LCD
- import_tasks: configure-boot.yml
- import_tasks: configure-x11.yml
- import_tasks: configure-touch.yml
