---
- name: Clean lib input conf
  file:
    state: absent
    path: /etc/X11/xorg.conf.d/40-libinput.conf

- name: Make sure xorg.conf.d exists
  file:
    state: directory
    path: /etc/X11/xorg.conf.d
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x

- include: raspbian-facts.yml
  when: ansible_distribution == 'Debian'

- include: ubuntu-facts.yml
  when: ansible_distribution == 'Ubuntu'

- import_tasks: boot-config.yml
