---
- name: Check that the boot cmdline file exists
  ansible.builtin.stat:
    path: "{{ boot_config_dir }}cmdline.txt"
  register: cmdline_file

- name: Read boot cmdline content
  ansible.builtin.command: "cat {{ boot_config_dir }}cmdline.txt"
  register: cmdline_content
  changed_when: false
  when: cmdline_file.stat.exists

- name: Set Raspbian facts
  ansible.builtin.set_fact:
    is_noobs: "{{ 'stdout' in cmdline_content and 'root=/dev/mmcblk0p7' in cmdline_content.stdout }}"
