---
- name: Make sure /boot/firmware exists for ubuntu distro
  file:
    state: directory
    path: /boot/firmware
    owner: root
    group: root
    mode: u=rwx,g=rx,o=x

- name: Set Ubuntu facts
  set_fact:
    boot_config_path: "/boot/firmware/config.txt"
