name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
env:
  ROLE_NAME: fedejaure.rpi_lcd
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install system deps
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root --only dev --only flakeheaven --sync

      - name: Linting
        shell: bash
        run: poetry run inv hooks

  tests:
    needs: linting
    name: molecule-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian10
          - debian11
          - ubuntu2004
          - ubuntu2204
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          path: "${{ env.ROLE_NAME }}"

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install system deps
        working-directory: "./${{ env.ROLE_NAME }}"
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root

      - name: Install playbooks requirements
        working-directory: "./${{ env.ROLE_NAME }}"
        shell: bash
        run: poetry run inv galaxy-install

      - name: Run safety check
        working-directory: "./${{ env.ROLE_NAME }}"
        shell: bash
        run: poetry run inv safety

      - name: Run Molecule tests
        working-directory: "./${{ env.ROLE_NAME }}"
        run: poetry run inv tests
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
