name: tests
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - develop
env:
  ROLE_NAME: fedejaure.rpi_lcd
jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Linting
        run: |
          pip install pre-commit
          pre-commit run --all-files

  tests:
    needs: linting
    name: molecule-${{ matrix.distro }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - debian9
          - debian10
          - ubuntu1804
          - ubuntu2004
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
        with:
          path: "${{ env.ROLE_NAME }}"

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install system deps
        working-directory: "./${{ env.ROLE_NAME }}"
        shell: bash
        run: |
          pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --no-root

      - name: Install playbooks requirements
        shell: bash
        run: poetry run inv galaxy-install

      - name: Run safety check
        working-directory: "./${{ env.ROLE_NAME }}"
        shell: bash
        run: poetry run inv safety

      - name: Run Molecule tests
        working-directory: "./${{ env.ROLE_NAME }}"
        run: poetry run inv tests --target ${{ matrix.target }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
